export const SET_CHATROOMS = "SET_CHATROOMS";
export const SET_MESSAGES = "SET_MESSAGES";
export const ADD_MESSAGE = "ADD_MESSAGES";
export const SET_CHAT_USERS = "SET_CHAT_USERS";
export const SET_CURRENT_CHATROOM = "SET_CURRENT_CHATROOM";
export const HANDLE_DELETED_MESSAGE = "HANDLE_DELETED_MESSAGE";
